### ISSUE TITLE
Google play music support

### ISSUE THREAD

**Issue by kltdwrds** [buckmaxwell/jukebox#54]
Or YT music!  Those two paid subscriptions are shared across users and are basically equivalent in my experience.

**Comment by veryser** [comment]
This 👆

**Comment by buckmaxwell** [comment]
Hey Kyle and Matt! I'm looking into it, the schedule is probably apple music followed by gplay/YT. Feel free to drop a PR ;)

Are you both on YT?

There is actually surprisingly little feature parity across the APIs for music services. Gplay actually doesn't even have an official one :/

 Also, this might be a dup of #38 but leaving open for now.

**Comment by kltdwrds** [comment]
Nice! closing in favor of #38 - interesting to see apple music neck and neck with Spotify in the US.
